name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests provided by bats
      run: |
        sudo apt install -y bats
        ./test.sh
